// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChz6LDE5mi8OfOzx0s3_p4NBhMWK0Zq2Y',
    appId: '1:331784033062:web:6696ed9a11abea5842a7e7',
    messagingSenderId: '331784033062',
    projectId: 'my-chat-app-cc59c',
    authDomain: 'my-chat-app-cc59c.firebaseapp.com',
    storageBucket: 'my-chat-app-cc59c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJXyQMkmylcYtUQ3lbhbFX84BDp14arEU',
    appId: '1:331784033062:android:fc4643be86b6e48242a7e7',
    messagingSenderId: '331784033062',
    projectId: 'my-chat-app-cc59c',
    storageBucket: 'my-chat-app-cc59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHbEaPVOn3Ngnc0nsOm7gziUH-L_4480',
    appId: '1:331784033062:ios:3c18cacebd31571642a7e7',
    messagingSenderId: '331784033062',
    projectId: 'my-chat-app-cc59c',
    storageBucket: 'my-chat-app-cc59c.appspot.com',
    iosBundleId: 'com.example.myChatsAppss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHbEaPVOn3Ngnc0nsOm7gziUH-L_4480',
    appId: '1:331784033062:ios:ae3b27a9b9009f5a42a7e7',
    messagingSenderId: '331784033062',
    projectId: 'my-chat-app-cc59c',
    storageBucket: 'my-chat-app-cc59c.appspot.com',
    iosBundleId: 'com.example.myChatsAppss.RunnerTests',
  );
}
